### ISSUE TITLE
Replace determineCpuCoresWithAffinity with Envoy's OptionsImplPlatform::getCpuCount

### ISSUE THREAD

**Issue by htuch** [envoyproxy/nighthawk#120]
I think there is some design history here, but it seems we should be able to use Envoy's `OptionsImplPlatform::getCpuCount` to determine the CPU core count. This would then allow us to also eliminate `PlatformUtilTest.CpusWithAffinity`, which is problematic in the Google import due to the use of `sched_setaffinity` (incompatible with the constraints in the shared test environment).

**Comment by oschaaf** [comment]
+1, `PlatformUtilTest.CpusWithAffinity` it looks like a worthy replacement, and we win by having less code to worry about. I think `OptionsImplPlatform::getCpuCount` wasn't around when we added `PlatformUtilTest.CpusWithAffinity` ourselves.
