### ISSUE TITLE
Support fortio output format

### ISSUE THREAD

**Issue by nareddyt** [envoyproxy/nighthawk#155]
Creating this issue to track support to render results in fortio's web UI.

Currently, I am not sure where to find the specification for the format that fortio expects.

I can work on this issue if needed! But I'm a little busy for the next week.

**Comment by nareddyt** [comment]
Feel free to assign this issue to me! I'll try to get started on this next week.

**Comment by oschaaf** [comment]
Closing this, as this was resolved via #168, #225, #226, #255, #265, and #298
