### ISSUE TITLE
Create a PR pre-merge checklist for maintainers

### ISSUE THREAD

**Issue by oschaaf** [envoyproxy/nighthawk#230]
For new maintainers it would be helpful to have a checklist before merging PR's.
Starting out with a single item that triggered the idea:

- Does the PR have breaking changes? Then that should be made explicit and on top in the version history file.
- Call out updating the Envoy dependency - what should be synced.
- Features should be added to the version history
-  no breaking changes to the proto api allowed

**Comment by oschaaf** [comment]
@htuch do you have anything to add? I'll take care of creating a PR to add the file, but maybe we can assemble the contents here?

**Comment by htuch** [comment]
I think we should include even functional additions in the version history (similar to Envoy). On a related note, I think now that NH is being used by folks other than you and I, we need to end the practice of any breaking proto changes. So, maybe call that out.
