### ISSUE TITLE
Add support for open-loop latency measurement

### ISSUE THREAD

**Issue by oschaaf** [envoyproxy/nighthawk#25]
Currently Nighthawk is capable of doing closed-loop testing, which means that when configured resource limits are met (e.g. max connections, max streams), no new requests will be issued, even when that means not reaching the requested request pacing configuration (this wil show up in the output as a time-spend-blocked histogram).
In real life, clients will not wait like that, and supporting open-loop testing will help measuring latencies under these circumstances.

An important part of this feature is that load generation should auto-terminate upon detecting a certain amount of in-flight requests, and maybe when it detects certain resource shortages (like running out of file descriptors).

**Comment by oschaaf** [comment]
A lot of the prerequisites to this will land in #88 but to close this out it would be great to to add time-spend tracking closed-loop mode. In terms of implementation [that tracking should probably go here](https://github.com/envoyproxy/nighthawk/pull/88/files#diff-1d2696707301c1f4e20ca097e73e5891R199).

**Comment by mum4k** [comment]
@oschaaf can you help me by expanding on what is missing here? I was under the impression that we have all we need for the open loop mode. I see the comment about "time-spend tracking closed-loop mode", but am not clear on what it means.

**Comment by oschaaf** [comment]
This was fixed via #177. The line you refer to misses the word ‘blocking’: We track time spend waiting on the server while sending one or more new requests is due. We named that blocking. 

Closing this as there’s nothing remaining to be done here.
