### ISSUE TITLE
Investigate variability of TimingVerificationTest

### ISSUE THREAD

**Issue by eric846** [envoyproxy/nighthawk#263]
test/rate_limiter_test.cc:340
Expected equality of these values:
  getAcquisitionTimings(50_Hz, 1s)
    Which is: { 140, 200, 240, 360, 380, 400, 440, 460, 520, 540, 580, 600, 620, 640, 660, 680, 700, 740, 760, 780, 820, 840, 860, 880, 920, 940, 960, 980, 1000 }
  std::vector<int64_t>({120, 320, 380, 560, 580, 600, 620, 640, 660, 680, 700, 740, 760, 780, 840, 860, 880, 900, 920, 940, 960, 980, 1000})
    Which is: { 120, 320, 380, 560, 580, 600, 620, 640, 660, 680, 700, 740, 760, 780, 840, 860, 880, 900, 920, 940, 960, 980, 1000 }

Meanwhile the test is marked disabled.

**Comment by oschaaf** [comment]
I suspect we're running into this: https://stackoverflow.com/questions/48730363/if-we-seed-c11-mt19937-as-the-same-on-different-machines-will-we-get-the-same
Not sure how to address that. @htuch do you have any suggestions here?

**Comment by mum4k** [comment]
@oschaaf, now that we have a solution where we mock out the generator - do we still need to track this? Is there any downside to using the mock instead?

**Comment by oschaaf** [comment]
@mum4k Thinking some more about it, you are right, this is 100% fine now. So as far as I am concerned we can close this.

**Comment by mum4k** [comment]
Thank you @oschaaf.
