### ISSUE TITLE
Documentation is difficult to read for gRPC users

### ISSUE THREAD

**Issue by dubious90** [envoyproxy/nighthawk#278]
The API layer for figuring out how to use a gRPC endpoint is looking at the .proto file.  Most of the meet of the ExecutionStream StartRequest lives in https://github.com/envoyproxy/nighthawk/blob/master/api/client/options.proto

For a gRPC user, this is where you want to look for documentation on the fields. However, instead of explanations of the fields, each field points you towards a command line argument.  With over 20 fields, this is a lot of referencing back and forth to ask of a consumer, especially given that the names aren't 1:1 (requests_per_second to rps, RequestSource.uri vs --request_source)

**Comment by oschaaf** [comment]
As discussed on Slack, +1 from me. In my opinion, ideally we'd have a way to keep things in sync automatically, but this is viable short term and solves the immediate problem.

**Comment by dubious90** [comment]
@oschaaf Should we close this issue?  Or should we repurpose this towards a more longterm solution?

**Comment by oschaaf** [comment]
I would close this one, stating it was fixed via https://github.com/envoyproxy/nighthawk/pull/283, and then possibly open a new one to track automating this.

**Comment by dubious90** [comment]
Fixed via #283
