### ISSUE TITLE
gRPC service logs first ExecutionStream request to STDERR, but not further requests

### ISSUE THREAD

**Issue by dubious90** [envoyproxy/nighthawk#289]
After starting up the gRPC service, it will log ONLY the first request, which can make it harder to debug issues going on with the service.

We should log every request, though I'm not sure STDERR is the correct place to log any of these.

Also, while addressing this, we should make sure that it doesn't extend to other behaviors that may need to run on every request, but do not do so.

**Comment by dubious90** [comment]
@mum4k is P1 an accurate label for this bug?  Because we don't know what behaviors may be affected?

**Comment by mum4k** [comment]
@dubious90, yes with the understanding that it carries P1 priority only until we investigate the potential impact. If there will be no potential impact beyond the observed logging issue, we can decrease this to P2 for the actual fix.
