### ISSUE TITLE
nighthawk_client high CPU even at minimal load

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/nighthawk#334]
I am running the nighthawk client and seeing extremely high CPU usage even with minimal traffic. 

command:
`nighthawk_client httpbin.org/get --duration "60" --connections "1" --rps "5" --concurrency 1`

The CPU usage quickly spikes to using the full CPU. If I increase concurrency it will use more CPUs 

Calling a endpoint other than httpbin.org/get shows similar results. This was running on Kubernetes, I can reproduce locally in docker with

`docker run envoyproxy/nighthawk-dev:59683b759eb8f8bd8cce282795c08f9e2b3313d4 nighthawk_client httpbin.org/get --duration "60" --connections "1" --rps "1" --concurrency 1`. This is just a single RPS but uses a full core.

I have also done testing of nighthawk_client -> istio envoy -> istio envoy -> nighthawk_server. All CPU usage is low except nighthawk_client

**Comment by oschaaf** [comment]
This is expected because NH used a spin loop for producing accurate timings when idle. Behavior can be changed through configuration, the relevant code is here: https://github.com/envoyproxy/nighthawk/blob/c09fdcf66706c18c41c01d3f608ff4aa52dde1b2/source/common/sequencer_impl.cc#L145

**Comment by howardjohn** [comment]
That explains it, thanks!
