### ISSUE TITLE
Add functionality to flush metrics periodically and a few metrics (latency, total requests sent, ...)

### ISSUE THREAD

**Issue by qqustc** [envoyproxy/nighthawk#344]
Currently Nighthawk does not flush statistics and metrics in real time during its run. We plan to add the functionality to flush Nighthawk metrics periodically (at a configured time interval) to Envoy stats Sinks following the example of what has been done in Envoy.

We also plan to add new counters and histograms to monitor
number of total requests sent  		(counter)
request latency 				(histogram)
request/response header/body size		(histogram)
number of total requests blocked  		(counter)

/cc @mum4k

**Comment by oschaaf** [comment]
This sounds awesome. Some thoughts that are potentially relevant:

- I found this counter intuitive, but the tls counters aren't actually thread local. So at this time we explicitly use a namespace to isolate them per worker. At the time I did have - from the top of my head - a derived Envoy counter implementation which would track both shared and local counters. This would avoid having to use the namespaces to isolate. This may (or may not) be worth revisiting.
- Another thing is that there's also an [open issue](https://github.com/envoyproxy/nighthawk/issues/115), where we concluded we'd like to switch from HdrHistogram to libcirclhist. Envoy uses libcirclhist these days, so actually we could just switch to Envoy's internal histogram implementation. Upon doing so, we'd have a similar issue with the per worker namespace we use, like above with the counters. I have not looked into what it takes to address that.
- A cross cutting concern might be how we sync histograms. Do we want to shoot for a unified way of sync/merging histograms when we think about threads, processes, machines, etc? If so, the way Envoy facilitates merging of histograms to the master thread might seem low hanging fruit -- but it might not be ideal when also considering the other scenarios.

**Comment by qqustc** [comment]
Thanks Otto for the information!

- We plan to define per-worker Envoy counters and histograms by using the scope/namespace (similar to http_2xx counter in benchmark_client_impl.h), so the issue about tls counters aren't actually thread local should not matter here.

- Yes, our plan is to use Envoy's internal histogram implementation at per-worker level.

- Haven't decided on how we sync histograms but maybe it is natural to follow the way Envoy sync histograms.

**Comment by qqustc** [comment]
Thanks Otto for the information!

- We plan to define per-worker Envoy counters and histograms by using the scope/namespace (similar to http_2xx counter in benchmark_client_impl.h), so the issue about tls counters aren't actually thread local should not matter here.

- Yes, our plan is to use Envoy's internal histogram implementation at per-worker level.

- Haven't decided on how we sync histograms but maybe it is natural to follow the way Envoy sync histograms.


> This sounds awesome. Some thoughts that are potentially relevant:
> 
> * I found this counter intuitive, but the tls counters aren't actually thread local. So at this time we explicitly use a namespace to isolate them per worker. At the time I did have - from the top of my head - a derived Envoy counter implementation which would track both shared and local counters. This would avoid having to use the namespaces to isolate. This may (or may not) be worth revisiting.
> * Another thing is that there's also an [open issue](https://github.com/envoyproxy/nighthawk/issues/115), where we concluded we'd like to switch from HdrHistogram to libcirclhist. Envoy uses libcirclhist these days, so actually we could just switch to Envoy's internal histogram implementation. Upon doing so, we'd have a similar issue with the per worker namespace we use, like above with the counters. I have not looked into what it takes to address that.
> * A cross cutting concern might be how we sync histograms. Do we want to shoot for a unified way of sync/merging histograms when we think about threads, processes, machines, etc? If so, the way Envoy facilitates merging of histograms to the master thread might seem low hanging fruit -- but it might not be ideal when also considering the other scenarios.

**Comment by qqustc** [comment]
Closed this now since the metric flush functionality has been added.
