### ISSUE TITLE
Replace occurrences of "importing * from .." in python code 

### ISSUE THREAD

**Issue by oschaaf** [envoyproxy/nighthawk#371]
In some places we have code that looks like:

```python
from test.integration.utility import *
```

We should change those to explicitly import only what we need, for example:

```python
from test.integration.utility import assertEquals
```

**Comment by mum4k** [comment]
As discussed in #358, we should:

- ensure we only import packages or modules rather than functions, objects. E.g.:

```py
from test.integration import utility
```

- We should also rename "utility" into something more specific and meaningful so that statements like this read well. E.g.

```py
from test.integration import test

test.assertEqual
```

**Comment by oschaaf** [comment]
Linking https://github.com/envoyproxy/nighthawk/pull/337#discussion_r445789198 as a reminder the doc comment there should needs enhancement.
