### ISSUE TITLE
termination_predicate_test seems to be failing

### ISSUE THREAD

**Issue by qqustc** [envoyproxy/nighthawk#372]
run the test at master ( HEAD is now at bc72a52 integration-tests: tweaks to stabilize sanitizer runs (#357) )
(note since I'm still in the process of learning Github, I'm not totally sure about the failure if the failure is not reproducible)

/cc @oschaaf 

```
[ RUN      ] TerminationPredicateTest.AppendToChain
test/termination_predicate_test.cc:76: Failure
Expected equality of these values:
  child_predicate.get()
    Which is: NULL
  &(predicate.appendToChain(std::move(child_predicate)))
    Which is: 0x556f10640720
Stack trace:
  0x556f08d6bed0: Nighthawk::TerminationPredicateTest_AppendToChain_Test::TestBody()
  0x556f0b8a489b: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x556f0b89feb3: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x556f0b889950: testing::Test::Run()
  0x556f0b88a29b: testing::TestInfo::Run()
... Google Test internal frames ...

[  FAILED  ] TerminationPredicateTest.AppendToChain (168 ms)
```

**Comment by oschaaf** [comment]
That is odd; that PR passed in CI, and I can't really relate this to the changes you have in #368.
I'll take a closer look at the test to see if there's something machine or environment specific in there.

**Comment by oschaaf** [comment]
Ooh, I was going to say: looking at the offending code I can't imagine a sane way in which `child_predicate.get()` would return `NULL`, yet looking at the failure above it did. But then I looked closer. What if the `std::move()` is executed before `child_predicate.get()`? Ugh. I'll prepare a change.

```
  auto child_predicate = std::make_unique<StatsCounterAbsoluteThresholdTerminationPredicateImpl>(
      foo_counter, 0, TerminationPredicate::Status::FAIL);
  EXPECT_EQ(child_predicate.get(), &(predicate.appendToChain(std::move(child_predicate))));
```

**Comment by oschaaf** [comment]
@qqustc I created https://github.com/envoyproxy/nighthawk/issues/372 which I suspect will resolve this.
However, I don't have the means to confirm it, neither locally or in CI; would you be willing to do that? 
It's a super small change:
https://github.com/envoyproxy/nighthawk/pull/373/files

**Comment by oschaaf** [comment]
One question that pops up is: why didn't ubsan catch this?

**Comment by qqustc** [comment]
Thank you Otto.
The test now passed with your change in https://github.com/envoyproxy/nighthawk/pull/373/files

**Comment by oschaaf** [comment]
Great, thanks for confirming!
