### ISSUE TITLE
Deduplicate cluster setup code

### ISSUE THREAD

**Issue by oschaaf** [envoyproxy/nighthawk#387]
We have pretty similar code in scattered across three places:

- `ProcessImpl::addTracingCluster`
- `ProcessImpl::addRequestSourceCluster`
- `ProcessImpl::createBootstrapConfiguration`

It would be good to extract a helper for that which we can re-use across these calls.

**Comment by mum4k** [comment]
The linked files were refactored in https://github.com/envoyproxy/nighthawk/pull/719, so that this issue no longer applies.
