### ISSUE TITLE
OSX build broken

### ISSUE THREAD

**Issue by oschaaf** [envoyproxy/nighthawk#405]
Following a question on the slack channel, I tried to build Nighthawk's artifacts on OSX.

The following build error occurred:

```
ERROR: /Users/oschaaf/code/envoy-perf-vscode/nighthawk/source/common/BUILD:64:1: C++ compilation of rule '//source/common:nighthawk_common_lib' failed (Exit 1) wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' -iquote . -iquote ... (remaining 1191 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from source/common/statistic_impl.cc:1:
In file included from bazel-out/darwin-fastbuild/bin/source/common/_virtual_includes/nighthawk_common_lib/common/statistic_impl.h:6:
In file included from bazel-out/darwin-fastbuild/bin/include/nighthawk/common/_virtual_includes/base_includes/nighthawk/common/statistic.h:12:
In file included from bazel-out/darwin-fastbuild/bin/api/client/output.pb.h:38:
bazel-out/darwin-fastbuild/bin/api/client/options.pb.h:833:37: error: expected member name or ';' after declaration specifiers
  static constexpr VerbosityOptions DEBUG =
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
<command line>:2:15: note: expanded from here
#define DEBUG 1
              ^
1 error generated.
```

One of the proto api's has an [enum field named `DEBUG`](https://github.com/envoyproxy/nighthawk/blob/06a6a027adeb4970c853ad2f646acf28027e3fb6/api/client/options.proto#L44). On a hunch, I renamed that field, and the allows the build to succeed.
But that probably isn't an option because it would break our backwards compatibility guarantee, and I'm also not sure this is the right fix.

**Comment by dio** [comment]
Seems like we don't use that `#define DEBUG 1`? Probably:

```
$ bazelisk build --copt -UDEBUG //:nighthawk_client
```

Can be a solution.

**Comment by oschaaf** [comment]
@dio 

> Seems like we don't use that `#define DEBUG 1`? Probably:
> 
> ```
> $ bazelisk build --copt -UDEBUG //:nighthawk_client
> ```
> 
> Can be a solution.

I think that makes sense; but I'm also curious where that define originates from. So far I haven't been able to find it with a "regular" code search.

**Comment by dio** [comment]
My guess will be: that is added automatically when running fasbuild with -DDEBUG flag.

**Comment by oschaaf** [comment]
@dio Thanks, that greatly helps! 
Reading up over at https://docs.bazel.build/versions/master/user-manual.html

```
--compilation_mode (fastbuild|opt|dbg) (-c)
....
fastbuild means build as fast as possible: generate minimal debugging information (-gmlt -Wl,-S), and don't optimize. 
This is the default. Note: -DNDEBUG will not be set.
```

So that surely seems related, but now I'm curious why this specifically breaks on OSX and not on Linux.

**Comment by oschaaf** [comment]
Created https://github.com/envoyproxy/nighthawk/pull/411 to resolve

**Comment by kushthedude** [comment]
I am also getting the following error when I run `bazel test -c dbg //test/...`
```sh
ERROR: /private/var/tmp/_bazel_kush/8aa49dc757bf069da6c1e6fa4b8c3aaf/external/python_pip_deps/requirements.bzl:198:5: Traceback (most recent call last):
	File "/Users/kush/code/nighthawk/test/integration/BUILD", line 29
		py_library(<4 more arguments>)
	File "/Users/kush/code/nighthawk/test/integration/BUILD", line 57, in py_library
		requirement("zipp")
	File "/private/var/tmp/_bazel_kush/8aa49dc757bf069da6c1e6fa4b8c3aaf/external/python_pip_deps/requirements.bzl", line 198, in requirement
		fail(<1 more arguments>)
Could not find pip-provided dependency: 'zipp'
```
