### ISSUE TITLE
Simple way to wire in statistic into benchmark_client_impl

### ISSUE THREAD

**Issue by qqustc** [envoyproxy/nighthawk#409]
Several statistics are added to benchmark_client_impl in #381 which makes the constructor longer. In order to add more statistics in the future without exploding the constructor, we need to find a better way wire in the statistics.

\cc @oschaaf

**Comment by oschaaf** [comment]
@qqustc is this issue still actual? I think you made a change based which made the constructor take a struct with all the histograms as members, instead of passing all histograms as arguments, right? If so, I feel that suffices to close this, do you agree on that?

**Comment by qqustc** [comment]
Ah sorry, missed this.

Yes, I agree we can close this since the constructor takes a struct. Closed now.
