### ISSUE TITLE
python tests in ci coverage seems flaky.

### ISSUE THREAD

**Issue by wjuan-AFK** [envoyproxy/nighthawk#419]
I encountered this test failure in circle ci when making a PR related to python test coverage. Given that I did not touch the python code and my PR was adding a test, I figured that this was not due to a change I made. I reran the test a few times and then it passed. I believe that likely there is an issue with the flakiness of the python_test.
[TestCoverageFailure.txt](https://github.com/envoyproxy/nighthawk/files/4961783/TestCoverageFailure.txt)

**Comment by oschaaf** [comment]
Closing this as a duplicate of #362
