### ISSUE TITLE
Fortio output slightly different than the real fortio

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/nighthawk#422]
```
# cat /tmp/results/nighthawk |jq '.RetCodes'
{
  "200": "49988"
}
# cat /tmp/results/fortio  |jq '.RetCodes'
{
  "200": 50000
}
```

You can see in fortio the value is a number but in nighthawk a string

Versions:
```
FROM envoyproxy/nighthawk-dev:c3d7b475ddaafbe93b8223b84281463e3d3834a1 as nighthawk
FROM fortio/fortio:1.6.3 as fortio
```

Fortio command with `-json <path>`, nighthawk with `--output-format fortio`

**Comment by oschaaf** [comment]
Nice catch; 
So that field was defined as follows in 68e59719fe754401907c16e53156bf18cd0e4e65:

```proto3
 map<string, uint64> RetCodes = 11;
```

That looks allright to me; so to figure out why the integer typed map value gets serialized as a string, 
I think we need to dig into what happens in `Envoy::MessageUtil::getJsonStringFromMessage()`:

```c++
std::string MessageUtil::getJsonStringFromMessage(const Protobuf::Message& message,
                                                  const bool pretty_print,
                                                  const bool always_print_primitive_fields) {
  Protobuf::util::JsonPrintOptions json_options;
  ....
  std::string json;
  const auto status = Protobuf::util::MessageToJsonString(message, &json, json_options);
   ....
  return json;
}
```

This in turn would lead up to investigating `Protobuf::util::MessageToJsonString()` / if we need
to set a JsonPrintOption to make this work.

**Comment by oschaaf** [comment]
I wonder, there's `bool JsonPrintOptions::always_print_enums_as_ints` for `Protobuf::util::MessageToJsonString()`
By default they are rendered as strings.

I wonder if setting that would apply to values in maps too (or if it does exactly says what it does on the tin,
and stick to enums).
If it does turn out to fix our problem, we'd be lucky. If not, I think we need to propose an amendment to Protobuf to make
this happen.

**Comment by howardjohn** [comment]
Interesting, I am surprised it behaves that way...

By the way, this isn't actually breaking me in anyway, I just happened to notice this. Should have mentioned that in the original issue.

**Comment by oschaaf** [comment]
I was surprised too. It's probably tidier to serialize these as ints, though I think a lot of parser
might coerce the value into an int iff possible. But as far as I know that is not mandatory,  a strict parser would be right in
rejecting the value if it's using the proto schema to validate. I had a look at the protobuf serializer, and I'm pessimistic
that setting always_print_enums_as_ints would work. I think it woluld

**Comment by oschaaf** [comment]
Cross linking the [issue](https://github.com/protocolbuffers/protobuf/issues/7769 ) I filed in the protobuf repo.
