### ISSUE TITLE
Add safe proto diff helper

### ISSUE THREAD

**Issue by eric846** [envoyproxy/nighthawk#433]
Need to do this separately after test/adaptive_load/utility.h goes in.

The helper should do:
  EXPECT_EQ(message->DebugString(), expected_config.DebugString());
  EXPECT_TRUE(Envoy::MessageUtil()(*message, expected_config));

oschaaf:
I learned that with proto3 default values may not get serialised. I'm not 100% sure that equivalence here guarantees actual equivalence with respect to set/not-set/default-value. Therefore, to make sure no edge cases slip past, maybe it makes sense to also double down with MessageUtil()(message1, message1). This won't produce a helpful test message, so I'd put it after comparing the debug strings (which should produce a nice diff), maybe in a helper method.

**Comment by eric846** [comment]
Actually this isn't specific to adaptive_load, could go in an existing file.

**Comment by eric846** [comment]
Actually I don't see

**Comment by eric846** [comment]
This may be clearer than the construct with MessageUtil():

```
  EXPECT_TRUE(::Envoy::Protobuf::util::MessageDifferencer::Equivalent(*empty_config, expected_config));
```

**Comment by oschaaf** [comment]
Oh that's much nicer indeed

**Comment by oschaaf** [comment]
In the context of this issue, also making a note of a helpful review comment by @mum4k [1].
TIL there's ` ::testing::EqualsProto`
Sounds like we may want to use that as a replacement where applicable?

[1] https://github.com/envoyproxy/nighthawk/pull/522#discussion_r498507310

**Comment by mum4k** [comment]
Interestingly enough, `testing::EqualsProto` looks to be internal only:

https://github.com/google/googletest/issues/1761

While it is in the public documentation of gtest and gmock, it isn't actually present in the code. So back to plan B.

**Comment by mum4k** [comment]
Fyi, we now have a proto matcher:

https://github.com/envoyproxy/nighthawk/blob/9a6d7181ad886d9ad00a769c7d667d07ca2dc5dc/test/test_common/proto_matchers.h#L40-L48

**Comment by eric846** [comment]
\o/
