### ISSUE TITLE
Eliminate "using namespace Envoy"

### ISSUE THREAD

**Issue by eric846** [envoyproxy/nighthawk#488]
`using namespace Envoy;` is currently needed in Nighthawk in order to use `ENVOY_LOG` macros, which may have been written with the assumption that all code is in namespace `Envoy`.

Main usage:
https://github.com/envoyproxy/nighthawk/blob/6a0d3a3c9c306bf4914ddc460b6fd5931e1685e4/source/client/benchmark_client_impl.h#L34
Other usage:
https://github.com/envoyproxy/nighthawk/pull/483/files/2fc3d7a493d3be8c115b2bbff0249b777fa3f1bb#diff-33beda85dd6c5793ba41dad27d1c9a11

Some possibilities:

- Update the Envoy macros so they work in any namespace.
- Implement a Nighthawk compatibility layer for the `ENVOY_LOG` macros.
- Come up with a C++ trick that is safer than `using namespace`.

**Comment by oschaaf** [comment]
Next to the usage of `ENVOY_LOG_MISC` introduced in #483, in I think some of Envoy's macros related to histograms/counters/gauges may also be subject to this. In fact, after refreshing my memory, I think those are the sole reason for the `using namespace Envoy;` declarations in the current code base. For these, I suspect the most practical approach will be going in and amending the upstream macros.

**Comment by eric846** [comment]
That makes more sense now, I think `ENVOY_LOG` may work fine and it's only `ENVOY_LOG_MISC` that is the problem.

**Comment by oschaaf** [comment]
Yeah, it looks like ENVOY_LOG_MISC can be fixed with a small correction. I'm also looking into the other ones and hopefully I can create a PR to Envoy which upon merging allows us to get rid of 'using namespace Envoy' altogether.

**Comment by oschaaf** [comment]
Filed https://github.com/envoyproxy/envoy/pull/12827 for tweaking `ENVOY_LOG_MISC`, and https://github.com/envoyproxy/nighthawk/pull/489 to purge "using namespace Envoy" from own codebase:
it looks like the stats macros no longer need us to do this.

**Comment by oschaaf** [comment]
https://github.com/envoyproxy/nighthawk/pull/497 pulls the required change for `ENVOY_LOG_MISC` into Nighthawk

**Comment by oschaaf** [comment]
To complete this, maybe it would be good to add check in one of the check format scripts, that scans *.cc/*.h for lines containing "using namespace". We could then have a whitelist of things we agreed upon being OK, like  "using namespace std::chrono_literals". This should be all that needs to be done, as there's no "fix" required to balance it out.

**Comment by oschaaf** [comment]
This was closed via https://github.com/envoyproxy/nighthawk/pull/489
