### ISSUE TITLE
Fortio Output Transform: panic not reached error when using experimental_fortio_pedantic format

### ISSUE THREAD

**Issue by kushthedude** [envoyproxy/nighthawk#543]
#### Description

After updating the nighthawk image, when I tried to run test with experimental_fortio_pedantic format, I encounter following error
```sh
[21:45:38.894151][1][C] panic: not reached
```
**CLI Input**
```sh
docker run envoyproxy/nighthawk-dev:latest nighthawk_client --rps 10 --concurrency 1 --duration 5 https://www.github.com --output-format experimental_fortio_pedantic
```

The following input runs well while using other output formats.

**Comment by oschaaf** [comment]
Ouch. Let me look into that.
