### ISSUE TITLE
Consolidate a proper location for pushing benchmark docker images from CI

### ISSUE THREAD

**Issue by oschaaf** [envoyproxy/nighthawk#611]
[benchmarks/README.md](benchmarks/README.md) mentions `oschaaf/benchmark-dev:latest` as a location to source docker images from, which isn't right. We push images to https://hub.docker.com/r/envoyproxy/nighthawk-dev from CI, and we should try to consolidate a proper location for this, and push benchmark-dev images to it from CI.

Context:
[1] https://github.com/envoyproxy/nighthawk/pull/609#issuecomment-767282629

**Comment by oschaaf** [comment]
@htuch  could you help with this or point us to the right person to do so? It would be great to have `envoyproxy/nighthawk-benchmark-dev` or some such on dockerhub, as a place to push images to from CI.

**Comment by htuch** [comment]
@oschaaf is the ask from my end around Dockerhub namespace allocation or to make change in NH around this? @mum4k is finalizing an SoW here which should cover next steps in this area I think.

**Comment by oschaaf** [comment]
@htuch the ask is for a namespace allocation, I’d be up for proposing a NH change to use that (if no one objects to it of course — this way we can also get rid of the reference to my personal dockerhub for the benchmark image)

**Comment by htuch** [comment]
Got it. I think @lizan or @mattklein123 might have the Dockerhub permissions here.
