### ISSUE TITLE
Solidify output formatter implementations

### ISSUE THREAD

**Issue by oschaaf** [envoyproxy/nighthawk#625]
It would be good to go over the output formatter implementations and ensure that there are no ASSERT paths that can be hit when better handling of the condition that triggered it would be available. 
At the time of writing this there are two known ones:

- In some of the OutputFormatter implementations we rely on `getJsonStringFromMessageOrDie`,
which was introduced recently in an Envoy update. There's a variant of this method which doesn't die but instead returns an `absl::Status`, and that could be leveraged to enhance the flow here.
- The Fortio output formatter has a [known path](https://github.com/envoyproxy/nighthawk/blob/796c71832c3a9b44703c5b25805eec8227fb2c5d/source/client/output_formatter_impl.cc#L248) where it asserts when there are no a global result. This is suboptimal, as this can happen with some arguably silly yet valid configurations. Instead it would be better to instruct the Fortio UI to display an error, for which there are flags in its input json.

In general, it should be rare for any output formatter to terminate abnormally, but input can be transformed into output that reflects an error in the target format.

Context: this came up in review of https://github.com/envoyproxy/nighthawk/pull/621
Note: this affects only the CLI, and not the service, therefore we consider it not critical.

**Comment by Razdeep** [comment]
@oschaaf I would like to work on this issue, but I cannot find a variant of the method `getJsonStringFromMessageOrDie ` that returns `absl::Status`.

**Comment by oschaaf** [comment]
@Razdeep The idea would be to migrate all the cases where we use `getJsonStringFromMessageOrDie()` to `getJsonStringFromMessageOrError()`. The definition of that method resides over at:
https://github.com/envoyproxy/envoy/blob/302c5728b46934b3757f18e229d1e41ba6a92a68/source/common/protobuf/utility.h#L487
