### ISSUE TITLE
CI test_gcc failed due to VM ran out of memory

### ISSUE THREAD

**Issue by qqustc** [envoyproxy/nighthawk#686]
*Title*: *CI test_gcc failed due to VM ran out of memory*

On https://github.com/envoyproxy/nighthawk/pull/685:

https://app.circleci.com/pipelines/github/envoyproxy/nighthawk/2998/workflows/ddd631be-d9d2-4d06-ab4e-ac3c8b104195/jobs/27697

https://app.circleci.com/pipelines/github/envoyproxy/nighthawk/jobs/27701

Need to investigate why our memory usage went up and where we can look at historical usage.

/cc @mum4k

**Comment by mum4k** [comment]
Looks like the right path forward will be to follow Envoy and move from CircleCI to AZP CI. We're currently scoping this and expect to get to this in 1-3 months. We will keep the `test_gcc` disabled until we do.
