### ISSUE TITLE
Disambiguate common headers

### ISSUE THREAD

**Issue by htuch** [envoyproxy/nighthawk#70]
Today, header `-I` paths are setup so we have the following situation:
```
#include "common/api/api_impl.h"
#include "common/common/cleanup.h"
#include "common/common/thread_impl.h"
#include "common/event/dispatcher_impl.h"
#include "common/event/real_time_system.h"
#include "common/filesystem/filesystem_impl.h"
#include "common/frequency.h"
#include "common/network/utility.h"
#include "common/runtime/runtime_impl.h"
#include "common/thread_local/thread_local_impl.h"
#include "common/uri_impl.h"
#include "common/utility.h"
```
Some of these headers, e.g. `real_time_system.h`, come from Envoy's tree, effectively `@envoy//source/common/event/real_time_system.h`, others come from NH, e.g. `//source/common:uri_impl.h`.

Ideally we have a cleaner way to visually disambiguate this in the header block.

**Comment by oschaaf** [comment]
Closing, this was resolved via https://github.com/envoyproxy/nighthawk/commit/cbfbcd538493c6407e8ae13aee4331cff864f9fb plus https://github.com/envoyproxy/nighthawk/commit/24a11ff55e87c84cea22d7d8322d6b3402970e87
