### ISSUE TITLE
Integration test_http_request_release_timing is flakey

### ISSUE THREAD

**Issue by tomjzzhang** [envoyproxy/nighthawk#773]
test_http_request_release_timing is flakey and occasionally fails on related issues.

Examples: 
- https://app.circleci.com/pipelines/github/envoyproxy/nighthawk/3236/workflows/1ceee96c-6e15-4078-815f-5eb734de5bc2/jobs/30300
- https://app.circleci.com/pipelines/github/envoyproxy/nighthawk/3212/workflows/4d568d91-7edd-4631-af66-7f569d13e132/jobs/30116
- https://app.circleci.com/pipelines/github/envoyproxy/nighthawk/3244/workflows/e1edc3a9-578e-4741-8525-a64599e1174c/jobs/30310

**Comment by tomjzzhang** [comment]
Efforts to improve flakiness have been done in the past. E.g. #702 

We now rely on nighthawk's self reported worker duration instead of the total duration of duration. 

https://github.com/envoyproxy/nighthawk/blob/4f8b7294c992b85ffe054a941c144f476c754237/test/integration/test_integration_basics.py#L702-L704

With this change, we expect the `actual_duration` to be less than the passed in client duration. However https://app.circleci.com/pipelines/github/envoyproxy/nighthawk/3236/workflows/1ceee96c-6e15-4078-815f-5eb734de5bc2/jobs/30300 indicates an actual_duration of 15.664131436 seconds when the passed in duration was 10 seconds.

**Comment by tomjzzhang** [comment]
Digging into the code and consulting @oschaaf, it appears that `execution_duration` is not 100% accurate. 

When `execution_duration` exceeds `duration` significantly that probably means that a lot of time elapsed between https://github.com/envoyproxy/nighthawk/blob/4f8b7294c992b85ffe054a941c144f476c754237/source/client/process_impl.cc#L518  and https://github.com/envoyproxy/nighthawk/blob/main/source/client/process_impl.cc#L533. This could mean that either the workers are waiting on connection pools to drain or a large consecutive block of time was stolen by another process or neighboring VM. 

Possible solutions could be:
1. tighten up the measured execution time within the workers through an explicit stopExecution() call which just timestamps execution end for later use. As already mentioned, there is some work that is being done after the workers complete, which probably shouldn't be included within the execution time. 
2. we could add a flag which tracks the amount of elapsed time between wakeups/event in the sequencer in a histogram. Envoy might already have metrics for this, but additional investigation would be required.

**Comment by mum4k** [comment]
This is now passing in AZP.
