### ISSUE TITLE
clean up Python dependencies

### ISSUE THREAD

**Issue by eric846** [envoyproxy/nighthawk#819]
- An error `TypeError: required field "lineno" missing from alias` appeared in #817 
  - In these tests:
    - `//test/integration/unit_tests:test_nighthawk_test_server`
    - `//test/integration/unit_tests:test_utility`
    - `//test:python_test`
  - Worked around by setting `--assert=plain` on the pytest command line
- Attempting to change `pytest==6.0.1` to `pytest>=6.0.1,<7` in requirements.txt led to `ERROR: REDACTED/nighthawk/test/integration/BUILD:32:11: no such package '@python_pip_deps//pypi__more_itertools': BUILD file not found in directory 'pypi__more_itertools' of external repository @python_pip_deps. Add a BUILD file to a directory to mark it as a package. and referenced by '//test/integration:integration_test_base_lean'`
- Some other errors and warnings: https://gist.github.com/eric846/51e6db632eae0760961681a65cb06eca

**Comment by mum4k** [comment]
Once this is fixed we should also undo the workaround (the addition of `--assert=plain` pytest argument) added in https://github.com/envoyproxy/nighthawk/pull/817.
