### ISSUE TITLE
Access to coverage reports via CircleCI UI lost 

### ISSUE THREAD

**Issue by oschaaf** [envoyproxy/nighthawk#95]
It used to be so that we could access coverage reports through CircleCI's UI.
The artifacts are still uploaded, but still the UI elements that allowed me to access coverage
reports for PR's no longer shows up.

**Comment by htuch** [comment]
@oschaaf have you tried logging out of CircleCI and back in with your GH ID?

**Comment by oschaaf** [comment]
@htuch no, but I just did so, and that worked!
Closing
