### ISSUE TITLE
If coverage fails, rerunning it will produce an error due to the coverage artifact being the same path

### ISSUE THREAD

**Issue by dubious90** [envoyproxy/nighthawk#960]
Reproduction:
Have a build that fails coverage_integration.
If you choose to rerun that, it gives the following error:
![image](https://user-images.githubusercontent.com/692481/210282026-820beebf-83ac-4e40-8b5b-07558ee531b3.png)

I wanted to confirm if this was a flake coverage, as I did not change any code. However, rerunning does not appear to be possible.

**Comment by mum4k** [comment]
We should be able to fix this by including something like `System.JobAttempt` in the artifact name (Azure [variables](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)).
